version: "3"

networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24

services:
  unbound:
    image: "mvance/unbound:latest"
    container_name: unbound
    restart: always
    hostname: "unbound"
    volumes:
      - "unbound_data:/opt/unbound/etc/unbound/"
    networks:
      private_network:
        ipv4_address: 10.2.0.4

  wireguard:
    depends_on: [unbound, pihole]
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata # Change to your timezone
      - SERVERPORT=51820
      - SERVERURL=oracle-wirehole.duckdns.org #optional - For use with DDNS (Uncomment to use)
      - PEERS=1 # How many peers to generate for you (clients)
      - PEERDNS=10.2.0.5 # Set it to point to pihole
      - INTERNAL_SUBNET=10.6.0.0

    volumes:
      - wirehole_data:/config
      - wirehole_data:/lib/modules
    ports:
      - "51820:51820/udp"
    dns:
      - 10.2.0.5 # Points to pihole
      - 10.2.0.4 # Points to unbound
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

    restart: always
    networks:
      private_network:
        ipv4_address: 10.2.0.3

  pihole:
    depends_on: [unbound]
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    hostname: pihole
    ports:
      - "80:80"
    dns:
      - 127.0.0.1
      - 10.2.0.4 # Points to unbound
    environment:
      TZ: "Asia/Kolkata"
      WEBPASSWORD: "" # Blank password - Can be whatever you want.
      ServerIP: 10.1.0.100 # Internal IP of pihole
      DNS1: 10.2.0.4 # Unbound IP
      DNS2: 10.2.0.4 # If we don't specify two, it will auto pick google.
      DNSSEC: "true"
    # Volumes store your data between container upgrades
    volumes:
      - "pihole_data:/etc/pihole/"
      - "/etc-dnsmasq.d:/etc/dnsmasq.d/"
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    networks:
      private_network:
        ipv4_address: 10.2.0.5

  portainer:
    depends_on: [wireguard]
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      private_network:
        ipv4_address: 10.2.0.6

volumes:
  unbound_data:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /home/ubuntu/wirehole/volumes/unbound
  wirehole_data:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /home/ubuntu/wirehole/volumes/wireguard
  pihole_data:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /home/ubuntu/wirehole/volumes/wireguard
  portainer_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/wirehole/volumes/portainer
